version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: xteamBack
      MYSQL_USER: root
      MYSQL_PASSWORD: "123456"
    ports:
      - "3306:3306"