# Generated by Django 5.0.4 on 2024-04-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="description1",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="description2",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="description3",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="description4",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="description5",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="price",
            field=models.FloatField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="title",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
