# Generated by Django 5.0.4 on 2024-04-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("surname", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("password", models.CharField(max_length=300)),
                ("phone", models.CharField(max_length=300)),
                ("status", models.CharField(default="inactive", max_length=200)),
                ("rol", models.CharField(default="user", max_length=200)),
                ("age", models.CharField(max_length=200)),
                ("img", models.CharField(max_length=300)),
                ("token", models.CharField(max_length=300)),
            ],
        ),
    ]
