# Generated by Django 5.0.4 on 2024-04-25 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                max_length=200,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="token",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
